---
# ldap_data_basic_example/tasks/acls.yml

- name: 'Set ACLs for ldapadmin and sssd-user'
  ldap_attr:
    dn: 'olcDatabase={2}mdb,cn=config'
    name: 'olcAccess'
    values: "{{ item }}"
  loop:
    - '{0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break'
    - '{1}to * by dn="uid=ldap-admin,ou=users,dc=training,dc=b1-systems,dc=de" manage by * break'
    - '{2}to * by dn="uid=sssd-user,ou=users,dc=training,dc=b1-systems,dc=de" read by * break'
    - '{3}to attrs=userPassword by self write by anonymous auth by users none'
    - '{4}to attrs=shadowLastChange by self write by * read'
