---
# ldap_data_basic_example/tasks/acls.yml

- name: 'Set ACLs for ldapadmin and sssd-user'
  ldap_attr:
    dn: 'olcDatabase={2}mdb,cn=config'
    name: 'olcAccess'
    values: "{{ item }}"
  loop:
    - '{0}to * by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage by * break'
    - '{1}to * by dn="uid=ldap-admin,ou=users,{{ base_dn }}" manage by * break'
    - '{2}to * by dn="uid=syncrepl,ou=system,{{ base_dn }}" write by * break'
    - '{3}to * by dn="uid=sssd-user,ou=users,{{ base_dn }}" read by * break'
    - '{4}to attrs=userPassword by self write by anonymous auth by users none'
    - '{5}to attrs=shadowLastChange by self write by * read'
    - '{6}to attrs=ou,employeeNumber,employeeType by self read by * none'
    - '{7}to * by self write by users read by * break'
    - '{8}to * by * none'
