---
# ldap_data_basic_example/tasks/debugging_script.yml

- name: 'Create debugging script'
  template:
    src: 'ldap_acl_debugging.sh.j2'
    dest: '/root/ldap_acl_debugging.sh'
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: 'Create the directory /root/LDAP_configuration_via_ansible/'
  file:
    path: '/root/LDAP_configuration_via_ansible/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: 'Create files to manually create and delete the users and groups'
  template:
    src: "{{ item }}.j2"
    dest: "/root/LDAP_configuration_via_ansible/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop:
    - 'step1_basedn.ldif'
    - 'step2_users_and_groups_ous.ldif'
    - 'step3_ldap-admin.ldif'
    - 'step4_sssd-user.ldif'
    - 'step5_regular_users.ldif'
    - 'DELETE_step1_basedn.ldapdelete'
    - 'DELETE_step2_users_and_groups_ous.ldapdelete'
    - 'DELETE_step3_ldap-admin.ldapdelete'
    - 'DELETE_step4_sssd-user.ldapdelete'
    - 'DELETE_step5_regular_users.ldapdelete'
    - 'acl_0_manage_permission_for_EXTERNAL.ldif'
    - 'acl_1_manage_permission_for_ldap-admin.ldif'
    - 'acl_2_read_permission_for_sssd-user.ldif'
    - 'acl_3_protect_userPassword.ldif'
    - 'acl_4_protect_shadowLastChange.ldif'
    - 'acl_5_protect_ou_employee_attributes.ldif'
    - 'acl_7_self_write_users_read.ldif'
    - 'acl_8_deny_access_to_everyone.ldif'
    - 'DELETE_acl_0_manage_permission_for_EXTERNAL.ldif'
    - 'DELETE_acl_1_manage_permission_for_ldap-admin.ldif'
    - 'DELETE_acl_2_read_permission_for_sssd-user.ldif'
    - 'DELETE_acl_3_protect_userPassword.ldif'
    - 'DELETE_acl_4_protect_shadowLastChange.ldif'
    - 'DELETE_acl_7_deny_access_to_everyone.ldif'
    - 'DELETE_acl_5_protect_ou_employee_attributes.ldif'
    - 'DELETE_acl_6_self_write_users_read.ldif'
