---
# ldap_data_basic_example/tasks/delete_everything.yml

- name: 'Delete regular users, sssd-user and ldap-admin'
  ldap_entry:
    dn: "{{ item }}"
    state: 'absent'
  loop:
    - "cn=Harry Potter,{{ users_ou }},{{ base_dn }}"
    - "cn=Hermione Granger,{{ users_ou }},{{ base_dn }}"
    - "cn=Ron Weasley,{{ users_ou }},{{ base_dn }}"
    - "uid=sssd-user,{{ users_ou }},{{ base_dn }}"
    - "uid=syncrepl,{{ system_ou }},{{ base_dn }}"
    - "uid=ldap-admin,{{ users_ou }},{{ base_dn }}"

- name: 'Delete posix_group gryffindor'
  ldap_entry:
    dn: "cn=gryffindor,{{ groups_ou }},{{ base_dn }}"
    state: 'absent'

- name: 'Delete OUs'
  ldap_entry:
    dn: "{{ item }}"
    state: 'absent'
  loop:
    - "{{ users_ou }},{{ base_dn }}"
    - "{{ groups_ou }},{{ base_dn }}"
    - "{{ system_ou }},{{ base_dn }}"

# The base DN cannot be deleted...

- name: 'Delete ACLs'
  ldap_attr:
    dn: 'olcDatabase={2}mdb,cn=config'
    name: 'olcAccess'
    values: '[]'
    state: 'absent'

- name: 'Delete the debugging script'
  file:
    path: '/root/ldap_acl_debugging.sh'
    state: 'absent'

- name: 'Delete the directory containing the LDIF files'
  file:
    path: '/root/LDAP_configuration_via_ansible/'
    state: 'absent'
