---
# ldap_data_basic_example/tasks/main.yml

- name: 'Load variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'

- name: 'Run install_packages.yml'
  include_tasks: install_packages.yml

- name: 'Run basedn_and_OUs.yml'
  include_tasks: basedn_and_OUs.yml

- name: 'Run ldap-admin.yml'
  include_tasks: ldap-admin.yml

- name: 'Run regular_users.yml'
  include_tasks: regular_users.yml
