---
# ldap_data_basic_example/tasks/main.yml

- name: 'Load variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'

- name: 'Run install_packages.yml'
  include_tasks: install_packages.yml

- name: 'Run basedn_and_OUs.yml'
  include_tasks: basedn_and_OUs.yml
  when: 'not remove_everything | bool'

- name: 'Run ldap-admin.yml'
  include_tasks: ldap-admin.yml
  when: 'not remove_everything | bool'

- name: 'Run sssd_user.yml'
  include_tasks: sssd_user.yml
  when: 'not remove_everything | bool'

- name: 'Run posix_group.yml'
  include_tasks: posix_group.yml
  when: 'not remove_everything | bool'

- name: 'Run regular_users.yml'
  include_tasks: regular_users.yml
  when: 'not remove_everything | bool'

- name: 'Run acls.yml'
  include_tasks: acls.yml
  when:
    - 'not remove_everything | bool'
    - 'apply_ACLs | bool'

- name: 'Run debugging_script.yml'
  include_tasks: debugging_script.yml
  when:
    - 'not remove_everything | bool'
    - 'add_debugging_script_and_ldif_files | bool'

- name: 'Run delete_everything.yml'
  include_tasks: delete_everything.yml
  when: 'remove_everything | bool'
