---
# ldap_data_basic_example/tasks/main.yml

- name: 'Run basedn_and_OUs.yml'
  include_tasks: basedn_and_OUs.yml

- name: 'Run ldap-admin.yml'
  include_tasks: ldap-admin.yml

- name: 'Run regular_users.yml'
  include_tasks: regular_users.yml
