---
# ldap_data_basic_example/tasks/regular_users.yml

- name: 'Create regular users'
  ldap_entry:
    dn: "{{ item.dn }},{{ users_ou }},{{ base_dn }}"
    objectClass:
      - 'posixAccount'
      - 'inetOrgPerson'
      - 'organizationalPerson'
      - 'person'
    attributes:
      loginshell: '/bin/bash'
      homeDirectory: "/home/{{ item.uid }}"
      userPassword: "{{ regular_users_password_hash }}"
      uid: "{{ item.uid }}"
      uidNumber: "{{ item.uidnumber }}"
      gidNumber: "{{ item.gidnumber }}"
      sn: "{{ item.sn }}"
      givenName: "{{ item.givenname }}"
  with_items:
    - dn: 'cn=Harry Potter'
      uid: 'hpotter'
      uidnumber: '10001'
      gidnumber: '9999'
      sn: 'Potter'
      givenname: 'Harry'
    - dn: 'cn=Hermione Granger'
      uid: 'hgranger'
      uidnumber: '10002'
      gidnumber: '9999'
      sn: 'Granger'
      givenname: 'Hermione'
    - dn: 'cn=Ron Weasley'
      uid: 'rweasley'
      uidnumber: '10003'
      gidnumber: '9999'
      sn: 'Weasley'
      givenname:
        - 'Ronald'
        - 'Bilius'
  register: create_regular_users

- name: 'Create fact to ignore errors when in check_mode and the user would be created'
  set_fact:
    ignore_errors_regular_users: 'true'
  when: 'create_regular_users.changed | bool and ansible_check_mode | bool'
  check_mode: 'false'

- name: 'Make sure all attributes are correct for Harry Potter'
  ldap_attr:
    dn: "cn=Harry Potter,{{ users_ou }},{{ base_dn }}"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
  loop: "{{ user_details | dict2items }}"
  vars:
    user_details:
      loginShell: '/bin/bash'
      homeDirectory: '/home/hpotter'
      userPassword: "{{ regular_users_password_hash }}"
      uid: 'hpotter'
      uidNumber: '10001'
      gidNumber: '9999'
      sn: 'Potter'
      givenName: 'Harry'
  ignore_errors: "{{ ignore_errors_regular_users }}"

- name: 'Make sure all attributes are correct for Hermione Granger'
  ldap_attr:
    dn: "cn=Hermione Granger,{{ users_ou }},{{ base_dn }}"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
  loop: "{{ user_details | dict2items }}"
  vars:
    user_details:
      loginShell: '/bin/bash'
      homeDirectory: '/home/hgranger'
      userPassword: "{{ regular_users_password_hash }}"
      uid: 'hgranger'
      uidNumber: '10002'
      gidNumber: '9999'
      sn: 'Granger'
      givenName: 'Hermione'
  ignore_errors: "{{ ignore_errors_regular_users }}"

- name: 'Make sure all attributes are correct for Ron Weasley'
  ldap_attr:
    dn: "cn=Ron Weasley,{{ users_ou }},{{ base_dn }}"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: 'exact'
  loop: "{{ user_details | dict2items }}"
  vars:
    user_details:
      loginShell: '/bin/bash'
      homeDirectory: '/home/rweasley'
      userPassword: "{{ regular_users_password_hash }}"
      uid: 'rweasley'
      uidNumber: '10003'
      gidNumber: '9999'
      sn: 'Weasley'
      givenName:
        - 'Ronald'
        - 'Bilius'
  ignore_errors: "{{ ignore_errors_regular_users }}"
