---
# ldap_data_basic_example/tasks/replication_user_and_ou.yml

- name: 'Create syncrepl user'
  ldap_entry:
    dn: "uid=syncrepl,{{ system_ou }},{{ base_dn }}"
    objectClass:
      - 'top'
      - 'account'
      - 'simpleSecurityObject'
    attributes:
      userPassword: "{{ syncrepl_user_password_hash }}"
  register: create_syncrepl_user

- name: 'Create fact to ignore errors when in check_mode and the user would be created'
  set_fact:
    ignore_errors_syncrepl_user: 'true'
  when: 'create_syncrepl_user.changed | bool and ansible_check_mode | bool'
  check_mode: 'false'

- name: 'Make sure all attributes are correct for syncrepl'
  ldap_attr:
    dn: "uid=syncrepl,{{ system_ou }},{{ base_dn }}"
    name: 'userPassword'
    values: "{{ syncrepl_user_password_hash }}"
    state: 'exact'
  ignore_errors: "{{ ignore_errors_syncrepl_user }}"

