---
# ldap_data_basic_example/tasks/sssd_user.yml

- name: 'Create sssd-user user'
  ldap_entry:
    dn: "uid=sssd-user,{{ users_ou }},{{ base_dn }}"
    objectClass:
      - 'top'
      - 'account'
      - 'simpleSecurityObject'
    attributes:
      userPassword: "{{ sssd_user_password_hash }}"
